defaults:
  - _self_

num_envs: 1
freq: 40                 # can only be divisible by 200-->(1,2,4,5,8,10,20,25,40,50,100,200)
camera_follow: True      #camera automatically adjusts to robot movement
env_name: warehouse       # obstacle, warehouse, hospital, office ,rivermark, terrain


sensor:
  enable_lidar: True
  enable_camera: True
  color_image: True
  depth_image: True
  semantic_segmentation: True

sim_app:
  anti_aliasing: 0
  width: 1280
  height: 720
  hide_ui: False
